SERVICE_HOST: localhost
SERVICE_PORT: 8080
SQL_DB_HOST: localhost
SQL_DB_PORT: 5432
SQL_DB_USER: postgres
SQL_DB_PASS: 5F4Dt9ky9dU$
POSTGRES_DB: postgres

spring:
  redis:
    host: localhost
    port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    rest:
      #base-path: /rest
      detection-strategy: ANNOTATED
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SQL_DB_HOST}:${SQL_DB_PORT}/${POSTGRES_DB}?sslmode=disable
    username: ${SQL_DB_USER}
    password: ${SQL_DB_PASS}
    hikari:
      maxLifetime: 300000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 1000000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # not recommended for production
        order_inserts: true
        jdbc:
          batch_size: 50

content:
  fs:
    filesystemRoot: /tmp/foo